Repository programming-in-th/programming.in.th, pull requests merged in 2020-06, with the labels that each got.

#429 ✨Change sumbissions path
  src/components/submissions/SubmissionsList.tsx
  src/components/tasks/TaskLayout.tsx
  src/pages/submissions/index.tsx
  src/pages/tasks/[...id].tsx
  src/pages/tasks/[id]/index.tsx
Labels: enhancement, feature

#437 💫Improve animation in tasks page
  src/components/submissions/SubmissionsList.tsx
  src/components/tasks/TaskLayout.tsx
  src/design/index.tsx
  src/pages/submissions/[id].tsx
  src/pages/submissions/index.tsx
  src/pages/tasks/[...id].tsx
Labels: enhancement

#438 ✨ Completed sync
  src/@types/submission.ts
  src/@types/task.ts
  src/config.ts
  src/pages/submissions/[id].tsx
Labels: enhancement

#439 :sparkles: Add task list
  package.json
  src/components/tasks/Table.tsx
  src/pages/tasks/index.tsx
  yarn.lock
Labels: enhancement, feature

#446 :lipstick: Improve submission UI
  src/components/Code.tsx
  src/pages/submissions/[id].tsx
Labels: enhancement

#445 :zap: Debounce filtering
  src/components/tasks/Table.tsx
Labels: enhancement

#448 ⚡️passHref to ChakraLink
  src/components/tasks/TaskLayout.tsx
Labels: feature

#456 🎨 Improving structure
  src/components/submissions/SubmissionsList.tsx
  src/components/tasks/Statement.tsx
  src/pages/submissions/[id].tsx
  src/utils/calculate.ts
Labels: enhancement

#459 Imp perf
  src/@types/submission.ts
  src/components/tasks/Submit/Comm.tsx
  src/components/tasks/Submit/Normal.tsx
  src/components/tasks/Submit/OutputOnly.tsx
  src/components/tasks/Submit/useSubmit.ts
  src/pages/submissions/[id].tsx
  src/utils/getTimestamp.ts
Labels: enhancement
